baseURL = 'http://zamedic.github.io/'
languageCode = 'en-us'
title = 'Marc Arndt'
theme = 'm10c'

[params]
author = "Marc Arndt"
description = "Marc Arndt's personal website"
menu_item_separator = " - "
avatar = "profile.jpg"


[[params.social]]
icon = "github"
name = "Github"
url = "https://github.com/zamedic"

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2